// Generated by CoffeeScript 1.3.3
(function() {
  var Schema;

  Schema = require('mongoose').Schema;

  exports.Geo = new Schema({
    lnglat: [Number],
    created: {
      type: Date,
      "default": Date.now
    },
    meta: {}
  });

}).call(this);
