// Generated by CoffeeScript 1.4.0
(function() {
  var controller;

  controller = require('./controller');

  exports.http = function(srvc, app) {
    var ctrl, express;
    express = require('express');
    ctrl = controller(srvc);
    if (app == null) {
      app = express();
    }
    app.use(express.bodyParser());
    app.post('/geo', ctrl.postGeos);
    app.post('/geojson', ctrl.postGeoJson);
    app.get('/post_geo', ctrl.postGeosByGet);
    app.get('/post_geojson', ctrl.postGeoJsonByGet);
    app.get('/post_params', ctrl.postGeoByGetParam);
    app.get('/geo/:id', ctrl.getGeo);
    app.get('/geojson/:id', ctrl.getGeoJson);
    app.get('/geo', ctrl.queryGeos);
    app.get('/geojson', ctrl.queryGeoJson);
    return app;
  };

  exports.socketio = function(srvc, server) {
    var io;
    io = require('socket.io').listen(server);
    io.sockets.on('connection', function(socket) {
      return socket.on('new geo', function(geo) {
        return srvc.createGeo(geo);
      });
    });
    srvc.on('new geo', function(geo) {
      return io.sockets.emit('new geo', geo);
    });
    return io;
  };

}).call(this);
